### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by jarlva** [alex-petrenko/faster-fifo#17]
I understand that you don't support Windows but maybe with a little guidance you can open it and Sample-Factory to the Windows community.
I would like to compile faster-fifo in Windows. Using MinGW-w64 GCC (http://mingw-w64.org/) and getting the following. 

```python
(torch) C:\Users\Jake\py\faster-fifo>python setup.py build_ext --inplace
C:\Users\Jake\miniconda3\envs\torch\lib\site-packages\setuptools\distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
running build_ext
building 'faster_fifo' extension
C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -I. -Icpp_faster_fifo/cpp_lib -IC:\Users\Jake\miniconda3\envs\torch\include -IC:\Users\Jake\miniconda3\envs\torch\include -c faster_fifo.cpp -o build\temp.win-amd64-3.7\Release\faster_fifo.o -std=c++14
C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -I. -Icpp_faster_fifo/cpp_lib -IC:\Users\Jake\miniconda3\envs\torch\include -IC:\Users\Jake\miniconda3\envs\torch\include -c cpp_faster_fifo/cpp_lib/faster_fifo.cpp -o build\temp.win-amd64-3.7\Release\cpp_faster_fifo\cpp_lib\faster_fifo.o -std=c++14
cpp_faster_fifo/cpp_lib/faster_fifo.cpp: In function 'void create_queue(void*, size_t)':
cpp_faster_fifo/cpp_lib/faster_fifo.cpp:112:16: warning: unused variable 'q' [-Wunused-variable]
     const auto q = new(queue_obj_memory) Queue(max_size_bytes);
                ^
cpp_faster_fifo/cpp_lib/faster_fifo.cpp: In function 'timeval wait(timeval, void**, void**)':
cpp_faster_fifo/cpp_lib/faster_fifo.cpp:130:5: error: 'timeradd' was not declared in this scope
     timeradd(&now, &wait_time, &wait_until);
     ^~~~~~~~
cpp_faster_fifo/cpp_lib/faster_fifo.cpp:130:5: note: suggested alternative: 'timeval'
     timeradd(&now, &wait_time, &wait_until);
     ^~~~~~~~
     timeval
cpp_faster_fifo/cpp_lib/faster_fifo.cpp:140:5: error: 'timersub' was not declared in this scope
     timersub(&wait_until, &now, &remaining);
     ^~~~~~~~
cpp_faster_fifo/cpp_lib/faster_fifo.cpp:140:5: note: suggested alternative: 'timeb'
     timersub(&wait_until, &now, &remaining);
     ^~~~~~~~
     timeb
error: command 'C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gcc.exe' failed with exit status 1
```

![image](https://user-images.githubusercontent.com/26058035/87917819-36a9a900-ca7e-11ea-97b4-6ccd5fc62640.png)

**Comment by alex-petrenko** [comment]
I apologize for the lack of support on this, this is an academic research project after all, so we had to sacrifice things like portability and platform support to make it happen (which is a very common practice in academia).

MinGW does not compile this because it is not fully POSIX-compliant. I think to make this work you need something like Cygwin which provides the full Unix-compatibility layer. We had to use POSIX mutexes here because generally there is no cross-platform alternative for multiprocessing mutexes and condition variables.

For the purposes of Sample Factory though it is much easier to write a stub that would fake faster-fifo API by routing all requests to multiprocessing.Queue. Performance impact should be negligible.

**Comment by alex-petrenko** [comment]
Ok, I actually went ahead and added this stub to the SampleFactory repo:
https://github.com/alex-petrenko/sample-factory/blob/master/utils/faster_fifo_stub.py

I don't have a Windows PC right now to check it, so I'd appreciate if you give it a try.
The queue is used like this now:

```
if os.name == 'nt':
    from utils.faster_fifo_stub import Queue as MpQueue
else:
    from faster_fifo import Queue as MpQueue
```

so as long as you don't install faster-fifo (just remove it from Conda env), it should not be a problem anymore.
That said, no one ever tested this codebase on Windows, so there might be other issues.

**Comment by jarlva** [comment]
Firstly, thank you for your willingness Alex.

I was not sure exactly how to apply the instructions. So I did the following:
. copied https://github.com/alex-petrenko/sample-factory/blob/master/utils/faster_fifo_stub.py to: sample-factory/utils/
. ensured faster-fifo is not in conda env,
. modified both learner.py and appo.py as follows:

```python
		# import faster_fifo	<remarked>
		if os.name == 'nt':
			from utils.faster_fifo_stub import Queue as MpQueue
		else:
			from faster_fifo import Queue as MpQueue

```
. search both files learner.py and appo.py for: "faster_fifo.Queue" and replaced with: MpQueue

Got: 
```bash
[2020-07-21 17:23:14,361][11288] Saved parameter configuration for experiment 0721-172314 not found!
[2020-07-21 17:23:14,361][11288] Starting experiment from scratch!
[2020-07-21 17:23:25,459][11288] Using 3 sets of trajectory buffers
[2020-07-21 17:23:25,559][11288] Initializing learners...
[2020-07-21 17:23:25,559][11288] Initializing the learner 0 for policy 0
Traceback (most recent call last):
  File "train_gym.py", line 131, in <module>
    sys.exit(main())
  File "train_gym.py", line 127, in main
    status = run_algorithm(cfg)
  File "c:\users\jake\py\sample-factory\run_algorithm.py", line 14, in run_algorithm
    status = algo.run()
  File "c:\users\jake\py\sample-factory\algorithms\appo\appo.py", line 673, in run
    self.init_workers()
  File "c:\users\jake\py\sample-factory\algorithms\appo\appo.py", line 411, in init_workers
    learner_worker.start_process()
  File "c:\users\jake\py\sample-factory\algorithms\appo\learner.py", line 114, in start_process
    self.process.start()
  File "C:\Users\Jake\miniconda3\envs\torch\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Jake\miniconda3\envs\torch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Jake\miniconda3\envs\torch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Jake\miniconda3\envs\torch\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Jake\miniconda3\envs\torch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects

(torch) C:\Users\Jake\py\SF_files>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Jake\miniconda3\envs\torch\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Jake\miniconda3\envs\torch\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

```

**Comment by alex-petrenko** [comment]
Yeah, just as I suspected, this is not related to faster-fifo, but to process creation.
Honestly, I don't know the reason for this error. I think there are just certain differences in behavior with respect to multiprocessing and sharing data structures. Sorry about that, Windows is just too different as a platform and non-trivial multiprocessing code would rarely work without some changes.

In particular, I think it complains about certain data structures that can't be pickled (on Windows) when the worker processes are forked. https://stackoverflow.com/questions/44144584/typeerror-cant-pickle-thread-lock-objects

**Comment by jarlva** [comment]
Hopefully at some point in the (near) future someone can get SF to work in Windows too.

**Comment by jarlva** [comment]
Here is some more info: Finally managed to get Windows with Linux subsystem 2 (WSL2) running. Managed to run a MNIST/pytorch with CUDA GPU acceleration (can see 17% gpu utilization). 
For some reason, SF, running the cartpole-v1 example gets stuck. I can see the GPU utilization spike to 100%, then falls to 0 and then nothing (no screen output and not even  creation of the training folder- as if everything freezes). Any idea what could it be?

```python
[2020-07-25 10:16:06,020][23893] Visible devices: 1
[2020-07-25 10:16:06,021][23893] Starting seed is not provided
[2020-07-25 10:16:06,022][23893] Waiting for the learner to initialize...
[2020-07-25 10:16:12,060][23893] No checkpoints found
[2020-07-25 10:16:12,060][23893] Did not load from checkpoint, starting from scratch!
[2020-07-25 10:16:12,061][23893] Broadcast model weights for model version 0
[2020-07-25 10:16:12,077][23893] Learner 0 initialized
[2020-07-25 10:16:12,078][23885] Initializing policy workers...
[2020-07-25 10:16:12,079][23885] Initializing policy worker 0 for policy 0
[2020-07-25 10:16:12,082][23885] Initializing policy worker 1 for policy 0
[2020-07-25 10:16:12,087][23885] Initializing actors...
[2020-07-25 10:16:12,091][23899] Set environment var CUDA_VISIBLE_DEVICES to '0' for inference process 0
[2020-07-25 10:16:12,100][23900] Set environment var CUDA_VISIBLE_DEVICES to '0' for inference process 0
[2020-07-25 10:16:12,106][23901] Initializing vector env runner 0...
[2020-07-25 10:16:12,108][23901] Initializing envs for env runner 0...
[2020-07-25 10:16:12,139][23900] Visible devices: 1
[2020-07-25 10:16:12,139][23900] Initializing model on the policy worker 0-1...
[2020-07-25 10:16:12,142][23899] Visible devices: 1
[2020-07-25 10:16:12,143][23899] Initializing model on the policy worker 0-0...
[2020-07-25 10:16:12,204][23901] Worker 0 uses CPU cores [0, 1]
[2020-07-25 10:16:12,234][23901] Decorrelating experience for 1 frames...
[2020-07-25 10:16:12,236][23885] Progress for 1 workers: 1/2 envs initialized...
[2020-07-25 10:16:12,236][23901] Decorrelating experience for 1 frames...
[2020-07-25 10:16:12,248][23901] Finished reset for worker 0
[2020-07-25 10:16:12,236][23885] Progress for 1 workers: 2/2 envs initialized...
[2020-07-25 10:16:12,249][23885] Waiting for policy worker 0-0 to finish initialization...
[2020-07-25 10:16:19,769][23900] Initialized model on the policy worker 0-1!
[2020-07-25 10:16:19,778][23899] Initialized model on the policy worker 0-0!
```

**Comment by alex-petrenko** [comment]
Looks like the main process gets stuck in this function:

```
    def finish_initialization(self):
        """Wait until policy workers are fully initialized."""
        for policy_id, workers in self.policy_workers.items():
            for w in workers:
                log.debug('Waiting for policy worker %d-%d to finish initialization...', policy_id, w.worker_idx)
                w.init()
                log.debug('Policy worker %d-%d initialized!', policy_id, w.worker_idx)
```

Policy workers signal a multiprocessing.Event when they finish initialization:

```
    def _init(self):
        log.info('Policy worker %d-%d initialized', self.policy_id, self.worker_idx)
        self.initialized = True
        self.initialized_event.set()
```

And the init() call in the first function waits for this event to be triggered:

```
    def init(self):
        self.task_queue.put((TaskType.INIT, None))
        self.initialized_event.wait()
```

The problem is, message "Policy worker ... initialized" never gets printed.
The last thing policy workers print is that model has been initialized. Ultimately this means that policy workers are getting stuck somewhere between line 206 and line 253 in policy_worker.py
Maybe some additional logging inserted between these lines can help you understand why they are getting stuck.

**Comment by visuallization** [comment]
Hey there just stumbled upon this and would really like to use sample factory on windows. I guess in essence "only" faster-fifo.cpp has to be ported, correct?

**Comment by alex-petrenko** [comment]
Hi @visuallization !
This question has been discussed a few times. I believe `faster-fifo` is not necessary for Sample Factory (it's just an optimization really). There's a wrapper that you can find here that should replace faster-fifo queue with regular multiprocessing.Queue: https://github.com/alex-petrenko/signal-slot/blob/main/signal_slot/queue_utils.py

There's a more significant problem. Sample Factory uses shared memory mechanism for communication between processes. I believe the current version is implemented in PyTorch using posix primitives and is not supported on Windows. This might have changed since the last time I researched this, but probably not.

Shared memory mechanism is pretty essential in Sample Factory, so I'm not sure if it's possible to make it work on Windows without figuring out torch.share_memory_(). Also: shared memory works differently for CPU RAM an VRAM, and Sample Factory uses both. For example, if CUDA shared memory now works in Windows, then it should be possible to use Sample Factory on Windows at least with GPU-accelerated environments like Brax or IsaacGym.

That said, I would really appreciate a WinAPI version of faster-fifo.cpp !! :) Not fluent in it myself so a contribution is very welcome!
